<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $data['title'] }}</title>
    <style>
        * { box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; color: #1e293b; font-size: 10px; margin: 0; padding: 24px; }
        .org-header { display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 3px solid #059669; padding-bottom: 10px; margin-bottom: 14px; }
        .org-name { font-size: 15px; font-weight: bold; color: #059669; }
        .report-title { font-size: 13px; font-weight: bold; color: #0f172a; }
        .meta { font-size: 9px; color: #64748b; margin-top: 3px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #10b981; color: #fff; text-align: left; padding: 6px 7px; font-size: 9px; text-transform: uppercase; letter-spacing: .04em; }
        td { padding: 5px 7px; border-bottom: 1px solid #e2e8f0; }
        tr:nth-child(even) td { background: #f8fafc; }
        .footer { margin-top: 14px; font-size: 8px; color: #94a3b8; text-align: center; }
        .empty { text-align: center; color: #94a3b8; padding: 20px 0; }
        @page { margin: 30px 24px; }
    </style>
</head>
<body>
    <div class="org-header">
        <div>
            <div class="org-name">{{ $org->name }}</div>
            <div class="meta">Procurement &amp; Supply Chain Report</div>
        </div>
        <div class="meta">
            Generated: {{ now()->format('d M Y H:i') }}<br>
            @if ($filters['date_from'] || $filters['date_to'])
                Period: {{ $filters['date_from'] ?: 'start' }} — {{ $filters['date_to'] ?: 'now' }}<br>
            @endif
            Filtered by: {{ $filters['status'] ?: 'all statuses' }} @if($filters['category_id']) · category @endif @if($filters['supplier_id']) · supplier @endif
        </div>
    </div>

    <div class="report-title">{{ $data['title'] }}</div>

    @if (empty($data['rows']))
        <p class="empty">No records match the selected criteria.</p>
    @else
        <table>
            <thead>
                <tr>
                    @foreach ($data['columns'] as $col)
                        <th>{{ $col }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($data['rows'] as $row)
                    <tr>
                        @foreach ($row as $cell)
                            <td>{{ $cell }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">Generated by {{ $org->name }} · {{ now()->format('Y-m-d H:i:s') }} · Confidential</div>
</body>
</html>
